# Generated by Django 5.2.5 on 2026-10-06 21:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=180)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('COSTO', 'Costo'), ('GASTO', 'Gasto')], max_length=8)),
            ],
            options={
                'verbose_name': 'categoría financiera',
                'verbose_name_plural': 'categorías financieras',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'centro de costo',
                'verbose_name_plural': 'centros de costo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=140)),
                ('tipo', models.CharField(choices=[('PERSONA', 'Persona'), ('EMPRESA', 'Empresa')], default='PERSONA', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15, unique=True, verbose_name='RUT')),
                ('nombres', models.CharField(max_length=90)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('moneda', models.CharField(default='CLP', max_length=3)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'lista de precios',
                'verbose_name_plural': 'listas de precios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('pais_origen', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'método de pago',
                'verbose_name_plural': 'métodos de pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10)),
            ],
            options={
                'verbose_name': 'período de nómina',
                'verbose_name_plural': 'períodos de nómina',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15, unique=True, verbose_name='RUT')),
                ('razon_social', models.CharField(max_length=140)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=180)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=120)),
                ('patente', models.CharField(max_length=12, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('simbolo', models.CharField(max_length=12, unique=True)),
            ],
            options={
                'verbose_name': 'unidad de medida',
                'verbose_name_plural': 'unidades de medida',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=24, unique=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('EMITIDA', 'Emitida'), ('RECIBIDA', 'Recibida'), ('ANULADA', 'Anulada')], default='EMITIDA', max_length=10)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='catalogo.bodega')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='catalogo.proveedor')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='catalogo.departamento')),
            ],
            options={
                'ordering': ['departamento__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ContratoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('horas_semanales', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)])),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='catalogo.cargo')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='catalogo.empleado')),
            ],
            options={
                'verbose_name': 'contrato laboral',
                'verbose_name_plural': 'contratos laborales',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=24, unique=True)),
                ('cantidad_planificada', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cantidad_producida', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PLANIFICADA', 'Planificada'), ('PROCESO', 'En proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PLANIFICADA', max_length=12)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_produccion', to='catalogo.bodega')),
            ],
            options={
                'verbose_name': 'orden de producción',
                'verbose_name_plural': 'órdenes de producción',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='LiquidacionSueldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_haberes', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('liquido', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='catalogo.contratolaboral')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='catalogo.periodonomina')),
            ],
            options={
                'verbose_name': 'liquidación de sueldo',
                'verbose_name_plural': 'liquidaciones de sueldo',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30, unique=True, verbose_name='SKU')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('punto_reorden', models.PositiveIntegerField(default=5)),
                ('imagen_url', models.URLField(blank=True, verbose_name='URL de imagen')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.marca')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.unidadmedida')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PrecioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('vigente_desde', models.DateField(default=django.utils.timezone.localdate)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precios', to='catalogo.listaprecio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'precio de producto',
                'verbose_name_plural': 'precios de productos',
                'ordering': ['-vigente_desde'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPRA', 'Entrada por compra'), ('VENTA', 'Salida por venta'), ('PROD_ENT', 'Entrada por producción'), ('PROD_SAL', 'Consumo de producción'), ('AJUSTE', 'Ajuste de inventario')], max_length=12)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('referencia', models.CharField(blank=True, max_length=80)),
                ('observacion', models.CharField(blank=True, max_length=220)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='catalogo.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'ordering': ['-fecha', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='catalogo.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'detalle de compra',
                'verbose_name_plural': 'detalles de compra',
            },
        ),
        migrations.CreateModel(
            name='ConsumoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='catalogo.ordenproduccion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_produccion', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'consumo de producción',
                'verbose_name_plural': 'consumos de producción',
            },
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(blank=True, max_length=40)),
                ('plazo_entrega_dias', models.PositiveSmallIntegerField(default=3)),
                ('costo_ultimo', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('preferente', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_producto', to='catalogo.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_proveedor', to='catalogo.proveedor')),
            ],
            options={
                'verbose_name': 'producto por proveedor',
                'verbose_name_plural': 'productos por proveedor',
            },
        ),
        migrations.CreateModel(
            name='RecetaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=24)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('rendimiento', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('activa', models.BooleanField(default=True)),
                ('producto_terminado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas_como_terminado', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'receta de producción',
                'verbose_name_plural': 'recetas de producción',
                'ordering': ['codigo', '-version'],
            },
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='catalogo.recetaproduccion'),
        ),
        migrations.CreateModel(
            name='ComponenteReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_como_componente', to='catalogo.producto')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='catalogo.recetaproduccion')),
            ],
            options={
                'verbose_name': 'componente de receta',
                'verbose_name_plural': 'componentes de recetas',
            },
        ),
        migrations.CreateModel(
            name='TransaccionFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('concepto', models.CharField(max_length=180)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('referencia', models.CharField(blank=True, max_length=80)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='catalogo.categoriafinanciera')),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='catalogo.centrocosto')),
            ],
            options={
                'verbose_name': 'transacción financiera',
                'verbose_name_plural': 'transacciones financieras',
                'ordering': ['-fecha', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=24, unique=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('PREPARACION', 'En preparación'), ('RUTA', 'En ruta'), ('ENTREGADO', 'Entregado')], default='PREPARACION', max_length=12)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='catalogo.transportista')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_turno', to='catalogo.empleado')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='catalogo.turno')),
            ],
            options={
                'verbose_name': 'asignación de turno',
                'verbose_name_plural': 'asignaciones de turnos',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=24, unique=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PAGADA', 'Pagada'), ('DESPACHADA', 'Despachada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='catalogo.cliente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('referencia', models.CharField(blank=True, max_length=80)),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='catalogo.metodopago')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='catalogo.venta')),
            ],
            options={
                'verbose_name': 'pago de venta',
                'verbose_name_plural': 'pagos de ventas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='catalogo.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='catalogo.venta')),
            ],
            options={
                'verbose_name': 'detalle de venta',
                'verbose_name_plural': 'detalles de venta',
            },
        ),
        migrations.CreateModel(
            name='DespachoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_despachadas', to='catalogo.despacho')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachos_venta', to='catalogo.venta')),
            ],
            options={
                'verbose_name': 'venta por despacho',
                'verbose_name_plural': 'ventas por despacho',
            },
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(fields=('departamento', 'nombre'), name='uq_departamento_cargo'),
        ),
        migrations.AddConstraint(
            model_name='contratolaboral',
            constraint=models.UniqueConstraint(fields=('empleado', 'fecha_inicio'), name='uq_contrato_empleado_inicio'),
        ),
        migrations.AddConstraint(
            model_name='liquidacionsueldo',
            constraint=models.UniqueConstraint(fields=('periodo', 'contrato'), name='uq_periodo_contrato'),
        ),
        migrations.AddConstraint(
            model_name='precioproducto',
            constraint=models.UniqueConstraint(fields=('producto', 'lista', 'vigente_desde'), name='uq_precio_producto_lista_fecha'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['producto', 'bodega', 'fecha'], name='idx_mov_prod_bod_fecha'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad', 0), _negated=True), name='ck_mov_cantidad_no_cero'),
        ),
        migrations.AddConstraint(
            model_name='detallecompra',
            constraint=models.UniqueConstraint(fields=('compra', 'producto'), name='uq_compra_producto'),
        ),
        migrations.AddConstraint(
            model_name='consumoproduccion',
            constraint=models.UniqueConstraint(fields=('orden', 'producto'), name='uq_orden_producto_consumo'),
        ),
        migrations.AddConstraint(
            model_name='productoproveedor',
            constraint=models.UniqueConstraint(fields=('producto', 'proveedor'), name='uq_producto_proveedor'),
        ),
        migrations.AddConstraint(
            model_name='recetaproduccion',
            constraint=models.UniqueConstraint(fields=('codigo', 'version'), name='uq_receta_codigo_version'),
        ),
        migrations.AddConstraint(
            model_name='componentereceta',
            constraint=models.UniqueConstraint(fields=('receta', 'componente'), name='uq_receta_componente'),
        ),
        migrations.AddIndex(
            model_name='transaccionfinanciera',
            index=models.Index(fields=['fecha', 'categoria'], name='idx_tx_fecha_categoria'),
        ),
        migrations.AddConstraint(
            model_name='asignacionturno',
            constraint=models.UniqueConstraint(fields=('empleado', 'fecha'), name='uq_empleado_turno_fecha'),
        ),
        migrations.AddConstraint(
            model_name='detalleventa',
            constraint=models.UniqueConstraint(fields=('venta', 'producto'), name='uq_venta_producto'),
        ),
        migrations.AddConstraint(
            model_name='despachoventa',
            constraint=models.UniqueConstraint(fields=('despacho', 'venta'), name='uq_despacho_venta'),
        ),
    ]
